"""empty message

Revision ID: 6bd9b55b0bc6
Revises: e601ec9804d8
Create Date: 2025-05-01 18:45:45.809649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd9b55b0bc6'
down_revision = 'e601ec9804d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=False))
        batch_op.drop_column('seeking_talent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
